language: go

go:
  - 1.9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnotify-dev

script:
 - go test -v ./... -coverprofile=coverage.txt

after_success:
 - bash <(curl -s https://codecov.io/bash)